### ISSUE TITLE
Allow to skip a task on the first load

### ISSUE THREAD

**Issue by patou** [criteo/loop#5]
It was greate if there are an option to skip a task on the first load, and just run it if a watch file is changed.
The task is long, and must be running once since a file is changed.
For exemple it's can be a npm or bower task.

**Comment by guillaumebort** [comment]
Well sometimes it can make sense but it is difficult to know for sure if it is required to run a task or not. If I take your example with `npm`, you can't be sure that it is not required to run it even on the first run, because perhaps it is the first run ever, or perhaps a `clean` has been made just before.

So I think it is preferable to keep the model simple.
